np.argmax(a, axis=0)的含义是a[0][j][k],a[1][j][k] (j=0,1,2,k=0,1,2,3)中最大值的索引.

从a[0][j][k]开始,a[0][j][k]对应的索引为((0,0,0,0),(0,0,0,0),(0,0,0,0))
拿a[0][j][k]和a[1][j][k]对应项作比较6大于-6,3大于-3,9大于-9,
所以更新这几个位置的索引,
将((0,0,0,0),(0,0,0,0),(0,0,0,0))更新为((0,0,0,0),(0,1,0,0),(1,0,1,0)).
...

最后axis = 0这一维消去了，得到的是 3x4的array


In [3]:
import numpy as np
a = np.array([
              [
                  [1, 5, 5, 2],
                  [9, -6, 2, 8],
                  [-3, 7, -9, 1]
              ],

              [
                  [-1, 5, -5, 2],
                  [9, 6, 2, 8],
                  [3, 7, 9, 1]
              ]
            ])

print(np.argmax(a, axis=0))

[[0 0 0 0]
 [0 1 0 0]
 [1 0 1 0]]


将a[i][0][k] a[i][1][k] a[i][2][k]比较
最后结果为 2x4 的array

((1, 2, 0, 1), (1,2,2,1))

In [5]:
print(np.argmax(a, axis=1))

[[1 2 0 1]
 [1 2 2 1]]


将a[i][j][0] a[i][j][1] a[i][j][2] a[i][j][3]比较
最后结果为 2x3 的array

((1, 0, 1), (1,0,2))

In [6]:
print(np.argmax(a, axis=2))

[[1 0 1]
 [1 0 2]]


同理np.max的结果也好理解

In [7]:
print(np.max(a, axis=0))
print(np.max(a, axis=1))
print(np.max(a, axis=2))

[[1 5 5 2]
 [9 6 2 8]
 [3 7 9 1]]
[[9 7 5 8]
 [9 7 9 8]]
[[5 9 7]
 [5 9 9]]


同理np.sum的结果也好理解

In [8]:
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=2))

[[ 0 10  0  4]
 [18  0  4 16]
 [ 0 14  0  2]]
[[ 7  6 -2 11]
 [11 18  6 11]]
[[13 13 -4]
 [ 1 25 20]]


In [10]:
i = np.array([0,1])
j = np.array([1,2])
k = np.array([0,3])
a[i][j]

IndexError: index 2 is out of bounds for axis 0 with size 2